### PR TITLE
Adding basic limit and offset to fetch

### PR DESCRIPTION
**Pull request by grieve**
Adding a limit and offset keyword param set to fetch, simple really, extra fixture and tests included.

### CODE REVIEW

**Comment by JoshAshby** [comment]
Outside of the additional tests, I don't see a reason to add this functionality as it already exists in the  https://github.com/JoshAshby/pyRethinkORM/blob/dev/rethinkORM/rethinkCollection.py#L65 `.limit(limit, offset)`  command. What benefit does this provide over that command?

**Comment by grieve** [comment]
I wrote it under the understanding of master, my bad I missed it in dev. I'll write the tests for the existing functionality 
On Fri, Feb 07, 2014 at 6:38 pm, Josh Ashby notifications@github.com wrote:Outside of the additional tests, I don't see a reason to add this functionality as it already exists in the  (https://github.com/JoshAshby/pyRethinkORM/blob/dev/rethinkORM/rethinkCollection.py#L65)[`.limit(limit, offset)`] command. What benefit does this provide over that command?

**Comment by JoshAshby** [comment]
No worries. I'll look it over and hopefully merge once you're done.

**Comment by JoshAshby** [comment]
I've gone ahead and added you as a collaborator on the repo also.

**Pull request closed without merging**
