### PR TITLE
Added offset and limit funcionality

### PR DESCRIPTION
**Pull request by justinrsmith**
Just added two little functions for offset and limits of results. I wrote a couple corresponding tests as well.

### CODE REVIEW

**Comment by justinrsmith** [comment]
Nevermind, just saw other pull request sitting out.

**Comment by JoshAshby** [comment]
Hey, if you want to get this merged in still, since that other pull request has been sitting for a few months and it's for the dev branch, (which as a branch probably won't get merged into master for another month or so (school eats away my time)), I'd be happy to let it in and release an updated version to pypi. The offset command is the only one missing from dev, as its merged into the `limit` command, but I'm happy with having them separate like this also.

Just say the word and I'll merge and probably update pypi later tonight when I have some time. I'm also adding you to the collaborators list like I have with the other people who have submitted pull-requests.

**Comment by JoshAshby** [comment]
And don't worry too much about the failed build on travis, it seems to be a problem with one of my tests that I'll look into.

**Comment by justinrsmith** [comment]
Ya go ahead and merge whenever you feel like. Thank you. I am using this project in a little side project I currently have going, really liking it. If I think of anything else I'll be in touch. Let me know if you have any questions.

**Comment by JoshAshby** [comment]
Awesome, glad to hear this is getting some use :D Keep an eye out for version 1.0.0 (currently the dev branch) as it has a few breaking changes but should clean parts of the interface up a bit.

**Comment by justinrsmith** [comment]
Sweet I will check that out and play around with it.

**Pull request merged**
